server:
  servlet:
    contextPath: /admin
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/SIGHT
    username: root
    password:
    driver:
      class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

messages:
  responseEmpty: "No se encuentran registros en la base datos."
  responseErrorFind: "No es posible consultar la información requerida."
  responseErrorCreate: "No es posible realizar el registro de la información suministrada."
  responseSuccessCreate: "Se ha registrado la información de forma exitosa."
